// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA44WC4u4Q4uf9Yc6lemsdjz1UtBAEbfmI',
    appId: '1:840032619672:android:a147b35c755c94645154ed',
    messagingSenderId: '840032619672',
    projectId: 'acadmate-50cbd',
    storageBucket: 'acadmate-50cbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLamWv5J85-r3oBHoDjZwP1evJtd-JXSQ',
    appId: '1:840032619672:ios:f30ab4ef5e7a9a245154ed',
    messagingSenderId: '840032619672',
    projectId: 'acadmate-50cbd',
    storageBucket: 'acadmate-50cbd.firebasestorage.app',
    androidClientId: '840032619672-9b5nnqhdp9o1srvfq9h1ssi3bfgdvmfd.apps.googleusercontent.com',
    iosClientId: '840032619672-ia1chbobuuqr2sgdkekqmpu01c9huiu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.acadmate',
  );

}